In [17]:
import pandas as pd
from pathlib import Path

file_path = Path("../data/raw/sensor_maintenance_data.csv")

data = pd.read_csv(file_path)
data[:5]

,Sensor_ID,Timestamp,Voltage (V),Current (A),Temperature (°C),Power (W),Humidity (%),Vibration (m/s²),Equipment_ID,Operational Status,...,Ambient Temperature (°C),Ambient Humidity (%),External Factors,X,Y,Z,Equipment Relationship,Equipment Criticality,Fault Detected,Predictive Maintenance Trigger
0,S_1,2024-01-01 00:00:00,110,0.5,20,55.0,40,0.20,E_1,Operational,...,20,40,Clear Weather,0,0,0,Independent,High,1,1
1,S_2,2024-01-01 01:00:00,111,0.6,21,66.6,41,0.25,E_2,Under Maintenance,...,21,41,Storm,1,1,1,Dependent,Medium,0,0
2,S_3,2024-01-01 02:00:00,112,0.7,22,78.4,42,0.30,E_3,Operational,...,22,42,Clear Weather,2,2,2,Dependent,High,0,0
3,S_4,2024-01-01 03:00:00,113,0.8,23,90.4,43,0.35,E_4,Under Maintenance,...,23,43,Storm,3,3,3,Independent,Medium,1,0
4,S_5,2024-01-01 04:00:00,114,0.9,24,102.6,44,0.40,E_5,Operational,...,24,44,Clear Weather,4,4,4,Dependent,High,0,1

In [ ]:
#Check data variables to encode in the database
print(f"These are the column names", data.columns)
print(f"Dataset has ", data.shape1[], "columns")
print(f"Dataset has", data.shape[0], "datapoints")

These are the column names Index(['Sensor_ID', 'Timestamp', 'Voltage (V)', 'Current (A)',
       'Temperature (°C)', 'Power (W)', 'Humidity (%)', 'Vibration (m/s²)',
       'Equipment_ID', 'Operational Status', 'Fault Status', 'Failure Type',
       'Last Maintenance Date', 'Maintenance Type', 'Failure History',
       'Repair Time (hrs)', 'Maintenance Costs (USD)',
       'Ambient Temperature (°C)', 'Ambient Humidity (%)', 'External Factors',
       'X', 'Y', 'Z', 'Equipment Relationship', 'Equipment Criticality',
       'Fault Detected', 'Predictive Maintenance Trigger'],
      dtype='str')
Dataset has  27 columns

In [19]:
len(data.columns)

27

In [20]:
data

,Sensor_ID,Timestamp,Voltage (V),Current (A),Temperature (°C),Power (W),Humidity (%),Vibration (m/s²),Equipment_ID,Operational Status,...,Ambient Temperature (°C),Ambient Humidity (%),External Factors,X,Y,Z,Equipment Relationship,Equipment Criticality,Fault Detected,Predictive Maintenance Trigger
0,S_1,2024-01-01 00:00:00,110,0.5,20,55.0,40,0.20,E_1,Operational,...,20,40,Clear Weather,0,0,0,Independent,High,1,1
1,S_2,2024-01-01 01:00:00,111,0.6,21,66.6,41,0.25,E_2,Under Maintenance,...,21,41,Storm,1,1,1,Dependent,Medium,0,0
2,S_3,2024-01-01 02:00:00,112,0.7,22,78.4,42,0.30,E_3,Operational,...,22,42,Clear Weather,2,2,2,Dependent,High,0,0
3,S_4,2024-01-01 03:00:00,113,0.8,23,90.4,43,0.35,E_4,Under Maintenance,...,23,43,Storm,3,3,3,Independent,Medium,1,0
4,S_5,2024-01-01 04:00:00,114,0.9,24,102.6,44,0.40,E_5,Operational,...,24,44,Clear Weather,4,4,4,Dependent,High,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,S_496,2024-01-21 15:00:00,115,0.5,25,57.5,45,0.20,E_46,Under Maintenance,...,20,40,Storm,95,45,15,Independent,Medium,1,0
496,S_497,2024-01-21 16:00:00,116,0.6,26,69.6,46,0.25,E_47,Operational,...,21,41,Clear Weather,96,46,16,Dependent,High,0,1
497,S_498,2024-01-21 17:00:00,117,0.7,27,81.9,47,0.30,E_48,Under Maintenance,...,22,42,Storm,97,47,17,Dependent,Medium,0,0
498,S_499,2024-01-21 18:00:00,118,0.8,28,94.4,48,0.35,E_49,Operational,...,23,43,Clear Weather,98,48,18,Independent,High,1,0
499,S_500,2024-01-21 19:00:00,119,0.9,29,107.1,49,0.40,E_50,Under Maintenance,...,24,44,Storm,99,49,19,Dependent,Medium,0,0